apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-php-app-deployment
spec:
  selector:
    matchLabels:
      app: simple-php-app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-php-app
    spec:
      containers:
        - name: simple-php-app
          image: 097084951758.dkr.ecr.us-east-1.amazonaws.com/sz-test-app:latest
          ports:
          - containerPort: 80