apiVersion: v1
kind: Service
metadata:
  name: simple-php-app
  labels:
    app.kubernetes.io/name: simple-php-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: simple-php-app
  ports:
    - name: svc-port
      port: 8080
      targetPort: app-port
      protocol: TCP
    - name: https
      port: 443
      targetPort: https